# Generated by Django 3.0.8 on 2020-07-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InternetBanking', '0003_transactionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='debit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
    ]
