# Generated by Django 3.0.8 on 2020-07-12 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InternetBanking', '0005_auto_20200712_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionhistory',
            name='amount',
        ),
    ]
