# Generated by Django 3.0.8 on 2020-07-12 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InternetBanking', '0006_remove_transactionhistory_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_number',
        ),
    ]
